apiVersion: v1
kind: Secret
metadata:
  name: gift-app
type: Opaque
stringData:
  database_url: "postgresql://giftuser:mysecretpassword@postgres-0.postgres-headless.gift-app.svc.cluster.local:5432/giftdb"