apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gift-app

resources:
  - ../../base
  - secret.yaml

patches:
  - target:
      kind: Deployment
      name: wishlist
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3