apiVersion: v1
kind: Secret
metadata:
  name: gift-app
type: Opaque
stringData:
  database_url: "postgresql://wishlist_user:${POSTGRES_PASSWORD}@postgres-0.postgres-headless.gift-app.svc.cluster.local:5432/wishlist"